[interface]
    name = "eth0"
    # (Required) The Device Name To Look For.
    device = "PCI:RTL8139"
    # (Required) One Of "Ethernet", "Wireless", "Loopback", "Auto"
    type = "Auto"
    # (Optional) The Network's Default Gateway, Ask DHCP Server If Not Present.
    default_gateway_v4 = "10.0.2.2"
    # (Optional) The DNS Servers Used To Resolve Names, Ask DHCP Server If Not Present.
    dns_v4 = ["8.8.8.8", "8.8.4.4"]
    # (Optional) The IP Address To Use, Ask DHCP Server If Not Present.
    ipv4 = "10.0.2.3"
    pingable = true