name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ production, trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        cargo install bootimage
        rustup component add llvm-tools-preview
        rustup component add rust-src
        sudo apt install qemu-system
    - name: Build
      run: make build

  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        cargo install bootimage
        rustup component add llvm-tools-preview
        rustup component add rust-src
        sudo apt install qemu-system
    - name: Test
      run: make test
